#!/bin/bash
rm -fr /Applications/Skype.app
rm -fr ~/Library/Application Support/Skype
rm ~/Library/Preferences/com.skype.skype.plist
rm -fr ~/Library/Address Book Plug-Ins/Skype/ABDialer.bundle
rm -fr ~/Library/Address Book Plug-Ins/SkypeABSMS.bundle
rm -fr ~/Library/Caches/com.skype.skype
